### PR TITLE
pass on error event to resulting EventEmitter object

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by juliangruber** [comment]
lgtm, but we should clean that up here: https://github.com/juliangruber/reconnect-core/pull/17/files#diff-168726dbe96b3ce427e7fedce31bb0bcL46

finally this is getting fixed :)

**Comment by ralphtheninja** [comment]
Or we could check in `onDisconnect()` if there was an error and just emit that. What do you think?

**Comment by ralphtheninja** [comment]
E.g. instead of adding an extra event listener:

```js
    function attempt (n, delay) {
      if(emitter.connected) return
      if(!emitter.reconnect) return

      emitter.emit('reconnect', n, delay)
      var con = createConnection.apply(emitter, args)
      emitter._connection = con

      function onDisconnect (err) {
        emitter.connected = false
        if(err) emitter.emit('error', err)
        con.removeListener('error', onDisconnect)
        con.removeListener('close', onDisconnect)
        con.removeListener('end'  , onDisconnect)

        //hack to make http not crash.
        //HTTP IS THE WORST PROTOCOL.
        if(con.constructor.name == 'Request')
          con.on('error', function () {})

        //emit disconnect before checking reconnect, so user has a chance to decide not to.
        emitter.emit('disconnect', err)

        if(!emitter.reconnect) return
        try { backoffMethod.backoff() } catch (_) { }
      }

      con
        .on('error', onDisconnect)
        .on('close', onDisconnect)
        .on('end'  , onDisconnect)


```

**Comment by juliangruber** [comment]
yeah, that's elegant :)

**Comment by ralphtheninja** [comment]
Updated. But hmm, is it enough to just check `if (err)`? `'close'` and `'end'` doesn't emit any data?

**Comment by juliangruber** [comment]
it shouldn't. the safe way would be to only do that in case of an `error` event though...hm tough. let's rather be correct than elegant.

**Comment by ralphtheninja** [comment]
Yes dad.

**Comment by juliangruber** [comment]
thanks man! published as `@0.2.2` as well as `@1.0.0` :tada:

**Comment by ralphtheninja** [comment]
:metal: Why publishing two versions? (Just curious).

**Comment by juliangruber** [comment]
i first did `publish patch` out of habit, then realized this is still a `0.` version so published `1.0.0` for semver awesomeness

**Comment by ralphtheninja** [comment]
`publish patch` as in `npm version patch` and `npm publish`?

**Comment by juliangruber** [comment]
@ralphtheninja i have a bash function for that:

```bash
publish() {
  npm version $1 || return 1
  git push || return 1
  git push --tags || return 1

  # skip publishing .private packages
  local private=`node -e "var pkg = require('./package'); process.stdout.write(String(pkg.private))"`
  [ "$private" == "true" ] && return

  if [[ $1 =~ - ]]; then
    npm publish --tag $1
  else
    npm publish
  fi
}
```

**Comment by ralphtheninja** [comment]
Aah nice one!

**Pull request merged**
